# Exploring eBay Car Sales Data


###  In this project, We'll work a data set of used cars from eBay kleinanzeigan,  a classified section of the German eBay website.

#####    It's just sampled 50,000 data points from the full dataset, And here is the columns info:
dateCrawled - When this ad was first crawled. All field-values are taken from this date.
name - Name of the car.
seller - Whether the seller is private or a dealer.
offerType - The type of listing
price - The price on the ad to sell the car.
abtest - Whether the listing is included in an A/B test.
vehicleType - The vehicle Type.
yearOfRegistration - The year in which which year the car was first registered.
gearbox - The transmission type.
powerPS - The power of the car in PS.
model - The car model name.
kilometer - How many kilometers the car has driven.
monthOfRegistration - The month in which which year the car was first registered.
fuelType - What type of fuel the car uses.
brand - The brand of the car.
notRepairedDamage - If the car has a damage which is not yet repaired.
dateCreated - The date on which the eBay listing was created.
nrOfPictures - The number of pictures in the ad.
postalCode - The postal code for the location of the vehicle.
lastSeenOnline - When the crawler saw this ad last online.
##### First of all, We import the Numpy & Pandas libraries. Then, You maybe noticed that we used encoding Argument with 'pd.read_csv'; because it is decoded by "Latin-1".
##### After that, We used DataFrame.info() and DataFrame.head() to undrastand more about our dataframe.

In [1]:
import pandas as pd
import numpy as np
auto=pd.read_csv('autos.csv',encoding='Latin-1')
auto

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [2]:
auto.info()
auto.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

##### in coming cammands, Beacause of not adhering The Column Labels of snakecase, We should change them manually by copying the dataframe columns label in a new series, and copy it's content and finally change it with the intended needs to be in Snakecase instead of CamelCase.

In [3]:
column_name=auto.columns.copy()
column_name

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [2]:
auto.columns=['date_Crawled', 'name', 'seller', 'offer_Type', 'price', 'ab_test',
       'vehicle_Type', 'registration_year', 'gear_box', 'power_PS', 'model',
       'odometer', 'registration_month', 'fuel_Type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_Of_Pictures', 'postal_Code',
       'last_Seen']
auto.head()

,date_Crawled,name,seller,offer_Type,price,ab_test,vehicle_Type,registration_year,gear_box,power_PS,model,odometer,registration_month,fuel_Type,brand,unrepaired_damage,ad_created,nr_Of_Pictures,postal_Code,last_Seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [5]:
auto.describe(include='all')

,date_Crawled,name,seller,offer_Type,price,ab_test,vehicle_Type,registration_year,gear_box,power_PS,model,odometer,registration_month,fuel_Type,brand,unrepaired_damage,ad_created,nr_Of_Pictures,postal_Code,last_Seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-11 22:38:16,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

In [6]:
auto['odometer'].value_counts(dropna=False)

150,000km    32424
125,000km     5170
100,000km     2169
90,000km      1757
80,000km      1436
70,000km      1230
60,000km      1164
50,000km      1027
5,000km        967
40,000km       819
30,000km       789
20,000km       784
10,000km       264
Name: odometer, dtype: int64

### Clean the Data
now It's time to valuate the columns and their entries by checking them one by one and see the correlations if is helpful.We catagorize them to 4 subcategories. first, which does not need any change, second which that have mostly one value that are candidates to be dropped, third which need more investigation and finally the last one which numeric data stored as text that needs to be cleaned.
We just talk about the last three ones.
the columns date_Crawled, ad_created,last_Seen are the date type which could be transform to numeric type, so they're in fourth sub.
And column odometer,price, could be easily transform to numeric column, so in fourth one.
The column nr_Of_Pictures does not have any valuable content; and the columns seller and offer_type have the same information and one is additional, So in the second one.
The Columns gear gear_box, power_PS, unrepaired_damage, fuel_Type, registration_month , model, because of some reasons need more investigation. So in the third one.

In [3]:
auto['price']=auto['price'].str.replace('$','')
auto['price']=auto['price'].str.replace(',','').astype(float)
auto['odometer']=auto['odometer'].str.replace('km','')
auto['odometer']=auto['odometer'].str.replace(',','').astype(float)
auto.rename({'odometer':'odometer_km'},axis=1,inplace=True)

In [8]:
auto.describe(include='all')

,date_Crawled,name,seller,offer_Type,price,ab_test,vehicle_Type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_Type,brand,unrepaired_damage,ad_created,nr_Of_Pictures,postal_Code,last_Seen
count,50000,50000,50000,50000,5.000000e+04,50000,44905,50000.000000,47320,50000.000000,47242,50000.000000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,NaN,2,8,NaN,2,NaN,245,NaN,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-11 22:38:16,Ford_Fiesta,privat,Angebot,NaN,test,limousine,NaN,manuell,NaN,golf,NaN,NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,NaN,25756,12859,NaN,36993,NaN,4024,NaN,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,9.840044e+03,NaN,NaN,2005.073280,NaN,116.355920,NaN,125732.700000,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,4.811044e+05,NaN,NaN,105.712813,NaN,209.216627,NaN,40042.211706,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,1000.000000,NaN,0.000000,NaN,5000.000000,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,1.100000e+03,NaN,NaN,1999.000000,NaN,70.000000,NaN,125000.000000,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,2.950000e+03,NaN,NaN,2003.000000,NaN,105.000000,NaN,150000.000000,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,7.200000e+03,NaN,NaN,2008.000000,NaN,150.000000,NaN,150000.000000,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,1.000000e+08,NaN,NaN,9999.000000,NaN,17700.000000,NaN,150000.000000,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

In [4]:
auto['odometer_km'].value_counts(dropna=False)

150000.0    32424
125000.0     5170
100000.0     2169
90000.0      1757
80000.0      1436
70000.0      1230
60000.0      1164
50000.0      1027
5000.0        967
40000.0       819
30000.0       789
20000.0       784
10000.0       264
Name: odometer_km, dtype: int64

In [5]:
auto['odometer_km'].describe()

count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [13]:
auto['odometer_km'].unique().shape

(13,)

In [15]:
auto['price'].value_counts(dropna=False).head(15)

0.0       1421
500.0      781
1500.0     734
2500.0     643
1200.0     639
1000.0     639
600.0      531
800.0      498
3500.0     498
2000.0     460
999.0      434
750.0      433
900.0      420
650.0      419
850.0      410
Name: price, dtype: int64

In [16]:
auto['price'].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

In [4]:
auto=auto[auto['odometer_km'].between(87500,150000)]
auto.describe(include='all')

,date_Crawled,name,seller,offer_Type,price,ab_test,vehicle_Type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_Type,brand,unrepaired_damage,ad_created,nr_Of_Pictures,postal_Code,last_Seen
count,41520,41520,41520,41520,4.152000e+04,41520,37209,41520.000000,39421,41520.000000,39310,41520.000000,41520.000000,37762,41520,32974,41520,41520.0,41520.000000,41520
unique,40294,32335,2,2,NaN,2,8,NaN,2,NaN,242,NaN,NaN,7,40,2,70,NaN,NaN,34391
top,2016-04-02 15:49:30,BMW_316i,privat,Angebot,NaN,test,limousine,NaN,manuell,NaN,golf,NaN,NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,73,41519,41519,NaN,21359,10912,NaN,31198,NaN,3407,NaN,NaN,24355,9097,28475,1593,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,8.237172e+03,NaN,NaN,2002.820111,NaN,114.490390,NaN,141736.030829,5.718015,NaN,NaN,NaN,NaN,0.0,50590.652192,NaN
std,NaN,NaN,NaN,NaN,5.072893e+05,NaN,NaN,35.023528,NaN,192.723287,NaN,17102.004255,3.731914,NaN,NaN,NaN,NaN,0.0,25622.203369,NaN
min,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,1910.000000,NaN,0.000000,NaN,90000.000000,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,9.990000e+02,NaN,NaN,1999.000000,NaN,70.000000,NaN,150000.000000,3.000000,NaN,NaN,NaN,NaN,0.0,30179.000000,NaN
50%,NaN,NaN,NaN,NaN,2.450000e+03,NaN,NaN,2003.000000,NaN,105.000000,NaN,150000.000000,6.000000,NaN,NaN,NaN,NaN,0.0,49328.000000,NaN
75%,NaN,NaN,NaN,NaN,5.500000e+03,NaN,NaN,2007.000000,NaN,147.000000,NaN,150000.000000,9.000000,NaN,NaN,NaN,NaN,0.0,71083.000000,NaN
max,NaN,NaN,NaN,NaN,1.000000e+08,NaN,NaN,9000.000000,NaN,17700.000000,NaN,150000.000000,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

In [5]:
auto=auto[auto['price'].between(0,16350)]
auto

,date_Crawled,name,seller,offer_Type,price,ab_test,vehicle_Type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_Type,brand,unrepaired_damage,ad_created,nr_Of_Pictures,postal_Code,last_Seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000.0,control,bus,2004,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500.0,control,limousine,1997,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350.0,test,kombi,2003,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,7900.0,test,bus,2006,automatik,150,voyager,150000.0,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,300.0,test,limousine,1995,manuell,90,golf,150000.0,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990.0,control,limousine,1998,manuell,90,golf,150000.0,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,250.0,test,NaN,2000,manuell,0,arosa,150000.0,10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590.0,control,bus,1997,manuell,90,megane,150000.0,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,999.0,test,NaN,2017,manuell,90,NaN,150000.0,4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,350.0,control,NaN,2000,NaN,0,NaN,150000.0,0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350.0,control,limousine,1999,manuell,101,a3,150000.0,11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,3999.0,test,kleinwagen,2007,manuell,75,clio,150000.0,9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,350.0,test,kombi,1999,manuell,101,vectra,150000.0,5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,5500.0,test,coupe,1990,manuell,205,scirocco,150000.0,6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,300.0,control,bus,1995,manuell,150,3er,150000.0,0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150.0,control,suv,2004,manuell,124,andere,150000.0,2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,3500.0,test,kombi,2003,manuell,131,a4,150000.0,5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,7999.0,control,bus,2010,manuell,120,NaN,150000.0,2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,90.0,control,kombi,1996,manuell,116,NaN,150000.0,4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,777.0,control,kleinwagen,1992,manuell,54,polo,125000.0,2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,0.0,control,NaN,2005,NaN,0,NaN,150000.0,0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,5250.0,control,kleinwagen,2007,manuell,110,cooper,150000.0,7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999.0,test,kombi,2004,automatik,204,e_klasse,150000.0,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,Angebot,80.0,test,kleinwagen,2002,manuell,60,2_reihe,150000.0,6,benzin,peugeot,ja,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,privat,Angebot,2850.0,test,kombi,2002,automatik,218,c_klasse,150000.0,7,benzin,mercedes_benz,nein,2016-03-14 00:00:00,0,41065,2016-03-16 07:19:04
32,2016-03-20 05:03:03,Corsa_mit_TÃœV_5.2016,privat,Angebot,350.0,control,kleinwagen,1999,manuell,0,corsa,150000.0,7,benzin,opel,NaN,2016-03-20 00:00:00,0,27619,2016-04-06 03:15:20
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,privat,Angebot,4800.0,test,kombi,2006,manuell,140,a3,150000.0,8,diesel,audi,nein,2016-03-15 00:00:00,0,61169,2016-04-07 13:15:31
34,2016-04-05 07:55:07,Bmw_530d__navi_tuv03/18,privat,Angebot,2600.0,test,kombi,2000,automatik,193,5er,150000.0,6,diesel,bmw,NaN,2016-04-05 00:00:00,0,95111,2016-04-07 12:15:47
35,2016-03-29 21:52:56,Ford_Mondeo,privat,Angebot,1200.0,test,kombi,1998,manuell,0,mondeo,150000.0,12,benzin,ford,nein,2016-03-29 00:00:00,0,52428,2016-04-06 08:45:35
36,2016-03-16 23:46:31,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,privat,Angebot,7500.0,test,kombi,2007,manuell,131,mondeo,150000.0,11,diesel,ford,nein,2016-03-16 00:00:00,0,34246,2016-04-05 16:21:16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49963,2016-03-26 19:52:59,Mercedes_Benz_B_200_CDI_Special_Edition,privat,Angebot,7600.0,control,bus,2007,manuell,140,b_klasse,125000.0,5,diesel,mercedes_benz,nein,2016-03-26 00:00:00,0,92272,2016-03-28 09:45:44
49964,2016-03-10 16:46:43,Audi_2_7_TDI_AVANT,privat,Angebot,12700.0,control,kombi,2010,automatik,192,a4,150000.0,5,diesel,audi,NaN,2016-03-10 00:00:00,0,54441,2016-04-07 01:15:47
49965,2016-03-11 10:53:51,Opel_Astra_1.6_Lenkradheizung~Sitzheizung,privat,Angebot,6700.0,test,limousine,2011,manuell,116,astra,125000.0,3,benzin,opel,nein,2016-03-11 00:00:00,0,37627,2016-03-15 01:44:57
49966,2016-04-02 19:49:19,CitroÃ«n_C1_1.0_**Euro4**TÃœV_OKT_2017**Scheiten...,privat,Angebot,1490.0,control,kleinwagen,2006,manuell,68,c1,150000.0,7,benzin,citroen,ja,2016-04-02 00:00:00,0,26603,2016-04-02 19:49:19
49967,2016-03-12 11:50:17,VW_Passat_2_0_TDI_comfortline,privat,Angebot,4999.0,test,kombi,2006,manuell,140,passat,150000.0,5,diesel,volkswagen,NaN,2016-03-12 00:00:00,0,70619,2016-03-17 09:45:12
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,privat,Angebot,2100.0,test,limousine,1986,automatik,90,andere,150000.0,9,diesel,mercedes_benz,nein,2016-04-01 00:00:00,0,40227,2016-04-05 13:16:35
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,privat,Angebot,4500.0,control,suv,2005,manuell,136,x_trail,150000.0,5,diesel,nissan,nein,2016-03-17 00:00:00,0,17379,2016-03-25 23:18:15
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,950.0,test,kleinwagen,2001,manuell,50,lupo,150000.0,4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,3300.0,control,bus,2004,automatik,150,vito,150000.0,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,6000.0,control,cabrio,2004,manuell,163,slk,150000.0,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,0.0,control,cabrio,1983,manuell,70,golf,150000.0,2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,9700.0,control,kleinwagen,2012,automatik,88,jazz,100000.0,11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,5900.0,test,kombi,1992,automatik,150,80,150000.0,12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,5500.0,control,limousine,2003,manuell,116,c_klasse,150000.0,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,900.0,control,limousine,1996,automatik,136,e_klasse,150000.0,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,400.0,control,kombi,1995,manuell,105,escort,125000.0,3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,2000.0,control,kombi,1998,manuell,115,astra,150000.0,12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,1950.0,control,kleinwagen,2004,manuell,0,fabia,90000.0,7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,600.0,test,kleinwagen,1999,manuell,101,focus,150000.0,4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,0.0,test,NaN,2000,NaN,0,NaN,150000.0,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,1000.0,control,NaN,1995,automatik,0,NaN,150000.0,0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,15900.0,control,limousine,2010,automatik,218,300c,125000.0,11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,9550.0,control,coupe,2001,manuell,231,3er,150000.0,10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,150.0,test,kleinwagen,1997,manuell,0,polo,150000.0,5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,500.0,control,NaN,2016,manuell,0,twingo,150000.0,0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,4800.0,control,kleinwagen,2009,manuell,120,andere,125000.0,9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,1650.0,control,kleinwagen,1997,manuell,0,NaN,150000.0,7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,5000.0,control,kombi,2001,automatik,299,a6,150000.0,1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,1980.0,control,cabrio,1996,manuell,75,astra,150000.0,5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,1250.0,control,limousine,1996,manuell,101,vectra,150000.0,1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [20]:
auto.describe(include='all')

,date_Crawled,name,seller,offer_Type,price,ab_test,vehicle_Type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_Type,brand,unrepaired_damage,ad_created,nr_Of_Pictures,postal_Code,last_Seen
count,39964,39964,39964,39964,39964.000000,39964,35698,39964.000000,37896,39964.000000,37819,39964.000000,39964.000000,36260,39964,31530,39964,39964.0,39964.000000,39964
unique,38823,31112,2,2,NaN,2,8,NaN,2,NaN,238,NaN,NaN,7,40,2,68,NaN,NaN,33465
top,2016-03-23 18:39:34,BMW_316i,privat,Angebot,NaN,test,limousine,NaN,manuell,NaN,golf,NaN,NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,73,39963,39963,NaN,20561,10532,NaN,30718,NaN,3379,NaN,NaN,23778,8895,27054,1537,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,3558.803899,NaN,NaN,2002.675083,NaN,109.948253,NaN,142286.557902,5.698754,NaN,NaN,NaN,NaN,0.0,50408.937168,NaN
std,NaN,NaN,NaN,NaN,3536.038723,NaN,NaN,35.644961,NaN,194.010425,NaN,16537.626480,3.740147,NaN,NaN,NaN,NaN,0.0,25620.312782,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1910.000000,NaN,0.000000,NaN,90000.000000,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,990.000000,NaN,NaN,1999.000000,NaN,68.000000,NaN,150000.000000,3.000000,NaN,NaN,NaN,NaN,0.0,29699.000000,NaN
50%,NaN,NaN,NaN,NaN,2299.000000,NaN,NaN,2002.000000,NaN,105.000000,NaN,150000.000000,6.000000,NaN,NaN,NaN,NaN,0.0,49090.000000,NaN
75%,NaN,NaN,NaN,NaN,4999.000000,NaN,NaN,2006.000000,NaN,141.000000,NaN,150000.000000,9.000000,NaN,NaN,NaN,NaN,0.0,70771.000000,NaN
max,NaN,NaN,NaN,NaN,16350.000000,NaN,NaN,9000.000000,NaN,17700.000000,NaN,150000.000000,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

## Exploring the Odometer & Price column
after finding the columns which need more investigation, first of all, we take a look on two columns 'Odometer' and price.
after a while, we notice that both the columns have some outliers.
to define how to size the outliers, we use the below formula:
    a) if it is greater than Q3+1.5(IQR)
    b) if it is lower than Q1-1.5(IQR)
we should these values which are in this criteria.
for 'price' column, the unforbidden criteria is (0,16350)
for 'odometer_km' column, the criteria is (87500,150000)
finally, We remove the rows step by step which aren't included.
and also we'll have 39964 rows!

In [21]:
auto['date_Crawled'].str[:10].value_counts( normalize=True,dropna=False).head(15)

2016-04-03    0.038184
2016-03-21    0.037534
2016-03-12    0.037384
2016-03-20    0.037309
2016-03-14    0.037158
2016-04-04    0.036733
2016-03-07    0.036283
2016-04-02    0.034706
2016-03-28    0.034631
2016-03-08    0.034231
2016-03-15    0.034006
2016-03-30    0.033981
2016-03-29    0.033830
2016-03-09    0.033805
2016-03-19    0.033580
Name: date_Crawled, dtype: float64

In [28]:
auto['date_Crawled'].str[:10].describe()

count          39964
unique            34
top       2016-04-03
freq            1526
Name: date_Crawled, dtype: object

In [8]:
auto['ad_created'].str[:10].value_counts(normalize=True, dropna=False).head(15)

2016-04-03    0.038460
2016-03-21    0.037659
2016-03-20    0.037309
2016-04-04    0.037259
2016-03-12    0.037234
2016-03-14    0.035607
2016-03-07    0.035132
2016-03-28    0.034606
2016-04-02    0.034306
2016-03-08    0.034206
2016-03-29    0.033931
2016-03-15    0.033805
2016-03-30    0.033780
2016-03-09    0.033680
2016-04-01    0.033180
Name: ad_created, dtype: float64

In [24]:
auto['ad_created'].str[:10].describe()

count          39964
unique            68
top       2016-04-03
freq            1537
Name: ad_created, dtype: object

In [25]:
auto['last_Seen'].str[:10].value_counts( normalize=True,dropna=False).head(15)

2016-04-06    0.209063
2016-04-07    0.122410
2016-04-05    0.118457
2016-03-17    0.029777
2016-04-02    0.025673
2016-04-03    0.025623
2016-03-12    0.025598
2016-03-30    0.025448
2016-04-04    0.025323
2016-03-31    0.024597
2016-04-01    0.024222
2016-03-29    0.023046
2016-03-22    0.022370
2016-03-28    0.022045
2016-03-20    0.022020
Name: last_Seen, dtype: float64

In [26]:
auto['last_Seen'].str[:10].describe()

count          39964
unique            34
top       2016-04-06
freq            8355
Name: last_Seen, dtype: object

### Explain Observation and Analyze the Results
after observing the three columns and see their trends, we can understand some features and make some predictions.
firs of all, for the "data_crawled",
As we see the dates, as we go forward in the dates,the abundance of them has a ascending rate.
second, the 'last_seen',
As we know both columns 'last_seen' & 'data_crawled' are related and there is an algorithm for the ad which posted and the times of showing it. You can see the unique values of thesee columns are same.
third, the 'ad_created' column, 
it has a swinging rate and the special times like weekend night(saturday night) are the busiest time of the week for example, And if You noticed, it has a ascending rate like the two ones too, Overall!

In [9]:
auto['registration_year'].describe()

count    39964.000000
mean      2002.675083
std         35.644961
min       1910.000000
25%       1999.000000
50%       2002.000000
75%       2006.000000
max       9000.000000
Name: registration_year, dtype: float64

### Exploring the 'registration_year'
as you see, there are some unreal and outliers.The year which eBay has just started is 1995 and these data is for until 2006. So the resume should be removed.

In [8]:
auto=auto[auto['registration_year'].between(1995,2006)]
auto['registration_year'].value_counts(normalize=True)

2000    0.111725
1999    0.102391
2005    0.097329
2003    0.091692
2001    0.091477
2004    0.090938
2002    0.085446
2006    0.084799
1998    0.082968
1997    0.069685
1996    0.048718
1995    0.042830
Name: registration_year, dtype: float64

### Removing the outlier values from 'registration_year'
as we mentioned the year which ebay is founded and this dataframe includes until 2006, We set the bound between1995-2006
#### Observing after removing
As you see, there is a yearly low rate in the first years, But after a while in 1998 and after that, It got a jump and spent some shiny years, but after that is has a steady rate, which could have lot of reasons....

In [8]:
auto

,date_Crawled,name,seller,offer_Type,price,ab_test,vehicle_Type,registration_year,gear_box,power_PS,model,odometer_km,registration_month,fuel_Type,brand,unrepaired_damage,ad_created,nr_Of_Pictures,postal_Code,last_Seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000.0,control,bus,2004,manuell,158,andere,150000.0,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500.0,control,limousine,1997,automatik,286,7er,150000.0,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350.0,test,kombi,2003,manuell,0,focus,150000.0,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,7900.0,test,bus,2006,automatik,150,voyager,150000.0,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,300.0,test,limousine,1995,manuell,90,golf,150000.0,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990.0,control,limousine,1998,manuell,90,golf,150000.0,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,250.0,test,NaN,2000,manuell,0,arosa,150000.0,10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590.0,control,bus,1997,manuell,90,megane,150000.0,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,350.0,control,NaN,2000,NaN,0,NaN,150000.0,0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350.0,control,limousine,1999,manuell,101,a3,150000.0,11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,350.0,test,kombi,1999,manuell,101,vectra,150000.0,5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,300.0,control,bus,1995,manuell,150,3er,150000.0,0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150.0,control,suv,2004,manuell,124,andere,150000.0,2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,3500.0,test,kombi,2003,manuell,131,a4,150000.0,5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,90.0,control,kombi,1996,manuell,116,NaN,150000.0,4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,0.0,control,NaN,2005,NaN,0,NaN,150000.0,0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999.0,test,kombi,2004,automatik,204,e_klasse,150000.0,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,Angebot,80.0,test,kleinwagen,2002,manuell,60,2_reihe,150000.0,6,benzin,peugeot,ja,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,privat,Angebot,2850.0,test,kombi,2002,automatik,218,c_klasse,150000.0,7,benzin,mercedes_benz,nein,2016-03-14 00:00:00,0,41065,2016-03-16 07:19:04
32,2016-03-20 05:03:03,Corsa_mit_TÃœV_5.2016,privat,Angebot,350.0,control,kleinwagen,1999,manuell,0,corsa,150000.0,7,benzin,opel,NaN,2016-03-20 00:00:00,0,27619,2016-04-06 03:15:20
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,privat,Angebot,4800.0,test,kombi,2006,manuell,140,a3,150000.0,8,diesel,audi,nein,2016-03-15 00:00:00,0,61169,2016-04-07 13:15:31
34,2016-04-05 07:55:07,Bmw_530d__navi_tuv03/18,privat,Angebot,2600.0,test,kombi,2000,automatik,193,5er,150000.0,6,diesel,bmw,NaN,2016-04-05 00:00:00,0,95111,2016-04-07 12:15:47
35,2016-03-29 21:52:56,Ford_Mondeo,privat,Angebot,1200.0,test,kombi,1998,manuell,0,mondeo,150000.0,12,benzin,ford,nein,2016-03-29 00:00:00,0,52428,2016-04-06 08:45:35
38,2016-03-21 15:51:10,Volkswagen_Golf_1.4_Special,privat,Angebot,2850.0,control,limousine,2002,manuell,75,golf,125000.0,2,benzin,volkswagen,nein,2016-03-21 00:00:00,0,63674,2016-03-28 12:16:06
39,2016-03-11 13:58:38,Mercedes_C_180_Kombi__zu_verkaufen,privat,Angebot,1450.0,test,kombi,1999,automatik,122,c_klasse,150000.0,6,benzin,mercedes_benz,nein,2016-03-11 00:00:00,0,12683,2016-04-06 15:17:52
40,2016-03-07 14:50:03,VW_Golf__4_Cabrio_2.0_GTI_16V___Leder_MFA_Alus...,privat,Angebot,3500.0,control,cabrio,1999,manuell,150,golf,150000.0,1,benzin,volkswagen,nein,2016-03-07 00:00:00,0,6780,2016-03-12 02:15:52
41,2016-03-10 10:46:08,Passat_3b_1.9_TDI_Highline__angemeldet_mit_tuv...,privat,Angebot,3200.0,test,kombi,2003,manuell,131,NaN,150000.0,7,NaN,volkswagen,nein,2016-03-10 00:00:00,0,28259,2016-04-06 20:19:08
44,2016-03-12 10:38:06,Zu_verkaufen,privat,Angebot,900.0,control,kleinwagen,1998,manuell,43,twingo,150000.0,7,benzin,renault,nein,2016-03-12 00:00:00,0,79725,2016-04-06 01:17:27
45,2016-03-12 17:39:55,Toyota_Starlet_1.3,privat,Angebot,1000.0,test,kleinwagen,1995,manuell,75,andere,150000.0,3,benzin,toyota,nein,2016-03-12 00:00:00,0,74597,2016-04-07 08:45:19
46,2016-03-31 10:53:28,BMW_mit__Lpg,privat,Angebot,9000.0,control,NaN,2005,automatik,0,NaN,150000.0,0,NaN,bmw,NaN,2016-03-31 00:00:00,0,12351,2016-04-06 03:44:41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49940,2016-03-11 14:52:16,Omas_Liebling,privat,Angebot,1200.0,control,kleinwagen,1995,manuell,98,3er,150000.0,3,benzin,bmw,nein,2016-03-11 00:00:00,0,74182,2016-03-16 23:18:18
49944,2016-03-15 17:48:16,SAAB_9_3__2_0t_SE__Automatik__Tempomat__Regens...,privat,Angebot,1000.0,control,limousine,2000,automatik,150,andere,150000.0,6,benzin,saab,nein,2016-03-15 00:00:00,0,4105,2016-04-02 17:17:12
49945,2016-04-04 12:54:29,omega_2_2_facelift_mit_neuem_tuev,privat,Angebot,1750.0,control,kombi,1999,manuell,144,omega,150000.0,12,benzin,opel,nein,2016-04-04 00:00:00,0,12355,2016-04-06 14:45:14
49952,2016-03-21 21:45:33,VW_POLO__9N3_Silber_1_2_Ltr._5_tuerer__96_tsd....,privat,Angebot,4300.0,control,kleinwagen,2005,manuell,64,polo,100000.0,3,benzin,volkswagen,nein,2016-03-21 00:00:00,0,35418,2016-04-07 01:44:58
49954,2016-03-17 19:48:47,328_Cabrio_Schalter,privat,Angebot,2490.0,control,cabrio,1997,manuell,193,NaN,150000.0,5,benzin,bmw,NaN,2016-03-17 00:00:00,0,45701,2016-03-20 22:17:56
49956,2016-03-28 22:39:12,Toyota_Yaris_1.3_VVT_i_Executive_MODEL_2007,privat,Angebot,4450.0,control,kleinwagen,2006,manuell,87,yaris,125000.0,9,benzin,toyota,nein,2016-03-28 00:00:00,0,44357,2016-03-30 15:45:26
49957,2016-03-10 10:52:01,Bmw_mit_LPG__super_zustand_2_Jahre_Tuev_klima,privat,Angebot,2900.0,test,coupe,2000,manuell,150,3er,150000.0,8,lpg,bmw,NaN,2016-03-10 00:00:00,0,41239,2016-03-11 10:18:32
49959,2016-03-28 21:53:21,Mercedes_Benz_C_180_T_Kompressor_Classic,privat,Angebot,4200.0,control,kombi,2003,manuell,143,c_klasse,150000.0,12,benzin,mercedes_benz,nein,2016-03-28 00:00:00,0,53844,2016-04-07 05:16:23
49960,2016-03-25 22:51:55,Ford_KA_zu_verschenken_***Reserviert***,privat,Angebot,0.0,control,kleinwagen,1999,manuell,60,ka,150000.0,6,benzin,ford,NaN,2016-03-25 00:00:00,0,34355,2016-03-25 22:51:55
49962,2016-03-14 17:57:15,Mitsubishi_Space_Star_1__3_L__Bj_2004_Standhei...,privat,Angebot,2200.0,test,limousine,2004,manuell,82,andere,150000.0,4,benzin,mitsubishi,ja,2016-03-14 00:00:00,0,45481,2016-03-15 13:45:08
49966,2016-04-02 19:49:19,CitroÃ«n_C1_1.0_**Euro4**TÃœV_OKT_2017**Scheiten...,privat,Angebot,1490.0,control,kleinwagen,2006,manuell,68,c1,150000.0,7,benzin,citroen,ja,2016-04-02 00:00:00,0,26603,2016-04-02 19:49:19
49967,2016-03-12 11:50:17,VW_Passat_2_0_TDI_comfortline,privat,Angebot,4999.0,test,kombi,2006,manuell,140,passat,150000.0,5,diesel,volkswagen,NaN,2016-03-12 00:00:00,0,70619,2016-03-17 09:45:12
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,privat,Angebot,4500.0,control,suv,2005,manuell,136,x_trail,150000.0,5,diesel,nissan,nein,2016-03-17 00:00:00,0,17379,2016-03-25 23:18:15
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,950.0,test,kleinwagen,2001,manuell,50,lupo,150000.0,4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,3300.0,control,bus,2004,automatik,150,vito,150000.0,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,6000.0,control,cabrio,2004,manuell,163,slk,150000.0,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,5500.0,control,limousine,2003,manuell,116,c_klasse,150000.0,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,900.0,control,limousine,1996,automatik,136,e_klasse,150000.0,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,400.0,control,kombi,1995,manuell,105,escort,125000.0,3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,2000.0,control,kombi,1998,manuell,115,astra,150000.0,12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,1950.0,control,kleinwagen,2004,manuell,0,fabia,90000.0,7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,600.0,test,kleinwagen,1999,manuell,101,focus,150000.0,4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,0.0,test,NaN,2000,NaN,0,NaN,150000.0,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,1000.0,control,NaN,1995,automatik,0,NaN,150000.0,0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,9550.0,control,coupe,2001,manuell,231,3er,150000.0,10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,150.0,test,kleinwagen,1997,manuell,0,polo,150000.0,5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,1650.0,control,kleinwagen,1997,manuell,0,NaN,150000.0,7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,5000.0,control,kombi,2001,automatik,299,a6,150000.0,1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,1980.0,control,cabrio,1996,manuell,75,astra,150000.0,5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,1250.0,control,limousine,1996,manuell,101,vectra,150000.0,1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [14]:
auto['brand'].value_counts(normalize=True,dropna=False)

volkswagen        0.206469
opel              0.126984
bmw               0.113161
mercedes_benz     0.094026
audi              0.078696
ford              0.076255
renault           0.058950
peugeot           0.033532
fiat              0.025454
seat              0.018812
mazda             0.017197
nissan            0.014899
citroen           0.012996
smart             0.012314
skoda             0.011488
toyota            0.010519
volvo             0.010232
mitsubishi        0.009298
alfa_romeo        0.007898
honda             0.007755
hyundai           0.006426
kia               0.005637
sonstige_autos    0.005134
suzuki            0.004883
chrysler          0.004667
mini              0.004380
daihatsu          0.002872
chevrolet         0.002441
subaru            0.002298
saab              0.002118
jeep              0.002118
daewoo            0.002010
rover             0.001975
land_rover        0.001651
porsche           0.001580
jaguar            0.001328
lancia            0.001221
dacia             0.000144
lada              0.000144
trabant           0.000036
Name: brand, dtype: float64

In [10]:
brand_counts = auto["brand"].value_counts(normalize=True)
common_brands = brand_counts[brand_counts > .05].index
print(common_brands)

/dataquest/system/env/python3/lib/python3.4/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


German manufacturers represent four out of the top five brands, almost 50% of the overall listings. Volkswagen is by far the most popular brand, with approximately double the cars for sale of the next two brands combined.

There are lots of brands that don't have a significant percentage of listings, so we will limit our analysis to brands representing more than 5% of total listings.

In [ ]:
brand_mean_prices = {}

for brand in common_brands:
    brand_only = auto[auto["brand"] == brand]
    mean_price = brand_only["price"].mean()
    brand_mean_prices[brand] = int(mean_price)

brand_mean_prices


Of the top 5 brands, there is a distinct price gap:

Audi, BMW and Mercedes Benz are more expensive
Ford and Opel are less expensive
Volkswagen is in between - this may explain its popularity, it may be a 'best of 'both worlds' option.

In [ ]:
bmp_series = pd.Series(brand_mean_prices)
pd.DataFrame(bmp_series, columns=["mean_mileage"])

In [ ]:
brand_mean_mileage = {}

for brand in common_brands:
    brand_only = autos[autos["brand"] == brand]
    mean_mileage = brand_only["odometer_km"].mean()
    brand_mean_mileage[brand] = int(mean_mileage)

mean_mileage = pd.Series(brand_mean_mileage).sort_values(ascending=False)
mean_prices = pd.Series(brand_mean_prices).sort_values(ascending=False)

In [ ]:

brand_info = pd.DataFrame(mean_mileage,columns=['mean_mileage'])
brand_info

In [ ]:
brand_info["mean_price"] = mean_prices
brand_info


The range of car mileages does not vary as much as the prices do by brand, instead all falling within 10% for the top brands. There is a slight trend to the more expensive vehicles having higher mileage, with the less expensive vehicles having lower mileage.